---
- hosts: ps_linux
  tasks:


  - name: check zabbix install
    shell: rpm -qa | grep zabbix-agent|cat
    register: zabbixcheck

  - name: debug
    debug: msg="{{zabbixcheck.stdout}}" #| search ('active')
    #when: zabbixcheck.stdout | search ('active')

  - block:
    - selinux : state=disabled

    - name: zabbix repo
      shell: rpm -Uvh https://repo.zabbix.com/zabbix/4.2/rhel/7/x86_64/zabbix-agent-4.2.0-1.el7.x86_64.rpm

    - name: echo zabbix not installed
      yum: name=zabbix-agent state=installed
         
    - name: copy conf file
      copy: src=/root/ansible/plaubooks/zabbix_agentd.conf dest=/etc/zabbix mode=0766

    - name: firewall enable rule
      firewalld: port=10050/tcp permanent=yes state=enabled

    - name: start service
      service: name=zabbix-agent state=restarted enabled=yes
 
    when: not zabbixcheck.stdout | search ('zabbix-agent')
